FROM markhobson/maven-chrome:jdk-11

LABEL maintainer="KieniL"
LABEL name="mavenchromebaseimage"
LABEL version="1.0.0"
LABEL author="KieniL"
LABEL contact="https://github.com/KieniL/base_images/issues"
LABEL documentation="https://github.com/KieniL/base_images"

ENV TZ EUROPE/BERLIN

WORKDIR /app

RUN rm -R /var/cache/apt/