FROM node:13.12.0-alpine

LABEL maintainer="KieniL"
LABEL name="nodebaseimage"
LABEL version="1.0"
LABEL author="KieniL"
LABEL contact="https://github.com/KieniL/base_images/issues"
LABEL documentation="https://github.com/KieniL/base_images"

WORKDIR /app

RUN rm -R /var/cache/apk/