name: Build Spring base image

on:
  push:
    branches: [ main ]
    paths:
      - 'spring/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'spring/**'

jobs:
  build-java:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build spring/ --file Dockerfile --tag luke19/spring-base-image:$(date +%s)
        docker tag luke19/spring-base-image:$(date +%s) luke19/spring-base-image:ubuntu-latest
        docker push luke19/spring-base-image:$(date +%s)
        docker luke19/spring-base-image:latest