name: Build nginx base image

on:
  push:
    branches: [ main ]
    paths:
      - 'nginx/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'nginx/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set variables
      run: |
        DATE_TMP=$(date +%s)
        echo "DATE=$DATE_TMP" >> $GITHUB_ENV

    - name: Build the Docker image
      run: |
        docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
        docker build -t luke19/nginx-base-image:${{ env.DATE }} nginx/
        docker tag luke19/nginx-base-image:${{ env.DATE }} luke19/nginx-base-image:latest
        docker push luke19/nginx-base-image:${{ env.DATE }}
        docker push luke19/nginx-base-image:latest